site_name: PITAMy-Dokumentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
